-- Per-edition credits («Над изданием работали») for МРД5/6, parsed from
-- chtivo.spb.ru/book-moguchij-russkij-dinozavr.html. Re-runnable.
-- Requires seed-periodicals.sql + seed-mrd5.sql (editions must exist).

BEGIN;

SELECT setval('"Workers_id_seq"', COALESCE((SELECT MAX(id) FROM "Workers"),0)+1, false);
SELECT setval('"EbookWorkers_id_seq"', COALESCE((SELECT MAX(id) FROM "EbookWorkers"),0)+1, false);
SELECT setval('"PrintedBookWorkers_id_seq"', COALESCE((SELECT MAX(id) FROM "PrintedBookWorkers"),0)+1, false);

-- Ensure worker rows exist (one per name+job).
INSERT INTO "Workers" (name, job) SELECT 'Ирина Курако', 'редактор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Ирина Курако' AND job='редактор');
INSERT INTO "Workers" (name, job) SELECT 'Ася Шарамаева', 'редактор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Ася Шарамаева' AND job='редактор');
INSERT INTO "Workers" (name, job) SELECT 'Глеб Кашеваров', 'редактор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Глеб Кашеваров' AND job='редактор');
INSERT INTO "Workers" (name, job) SELECT 'Александра Яковлева', 'редактор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Александра Яковлева' AND job='редактор');
INSERT INTO "Workers" (name, job) SELECT 'Наталья Атряхайлова', 'редактор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Наталья Атряхайлова' AND job='редактор');
INSERT INTO "Workers" (name, job) SELECT 'Вера Вересиянова', 'корректор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Вера Вересиянова' AND job='корректор');
INSERT INTO "Workers" (name, job) SELECT 'Александра Каменёк', 'корректор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Александра Каменёк' AND job='корректор');
INSERT INTO "Workers" (name, job) SELECT 'Катерина Гребенщикова', 'корректор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Катерина Гребенщикова' AND job='корректор');
INSERT INTO "Workers" (name, job) SELECT 'Софья Попова', 'корректор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Софья Попова' AND job='корректор');
INSERT INTO "Workers" (name, job) SELECT 'Полина Смолякова', 'корректор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Полина Смолякова' AND job='корректор');
INSERT INTO "Workers" (name, job) SELECT 'Лена Солнцева', 'иллюстратор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Лена Солнцева' AND job='иллюстратор');
INSERT INTO "Workers" (name, job) SELECT 'Маргарита Царева', 'иллюстратор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Маргарита Царева' AND job='иллюстратор');
INSERT INTO "Workers" (name, job) SELECT 'Екатерина Ковалевская', 'иллюстратор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Екатерина Ковалевская' AND job='иллюстратор');
INSERT INTO "Workers" (name, job) SELECT 'Екатерина Кравченко', 'дизайнер' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Екатерина Кравченко' AND job='дизайнер');
INSERT INTO "Workers" (name, job) SELECT 'Диана Гильманова', 'верстальщик' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Диана Гильманова' AND job='верстальщик');
INSERT INTO "Workers" (name, job) SELECT 'Анастасия Лукьянова', 'веб-мастер' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Анастасия Лукьянова' AND job='веб-мастер');
INSERT INTO "Workers" (name, job) SELECT 'Дарья Драхлер', 'продюсер' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Дарья Драхлер' AND job='продюсер');
INSERT INTO "Workers" (name, job) SELECT 'Анна Волкова', 'редактор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Анна Волкова' AND job='редактор');
INSERT INTO "Workers" (name, job) SELECT 'Никита Барков', 'редактор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Никита Барков' AND job='редактор');
INSERT INTO "Workers" (name, job) SELECT 'Софья Попова', 'редактор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Софья Попова' AND job='редактор');
INSERT INTO "Workers" (name, job) SELECT 'Нелли Реук', 'корректор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Нелли Реук' AND job='корректор');
INSERT INTO "Workers" (name, job) SELECT 'Анастасия Давыдова', 'корректор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Анастасия Давыдова' AND job='корректор');
INSERT INTO "Workers" (name, job) SELECT 'Татьяна Максимова', 'корректор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Татьяна Максимова' AND job='корректор');
INSERT INTO "Workers" (name, job) SELECT 'Анастасия Автухова', 'корректор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Анастасия Автухова' AND job='корректор');
INSERT INTO "Workers" (name, job) SELECT 'Александра Крученкова', 'корректор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Александра Крученкова' AND job='корректор');
INSERT INTO "Workers" (name, job) SELECT 'Ксения Шунькина', 'корректор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Ксения Шунькина' AND job='корректор');
INSERT INTO "Workers" (name, job) SELECT 'Кладбище Джо', 'иллюстратор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Кладбище Джо' AND job='иллюстратор');
INSERT INTO "Workers" (name, job) SELECT 'Екатерина Апенько', 'иллюстратор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Екатерина Апенько' AND job='иллюстратор');
INSERT INTO "Workers" (name, job) SELECT 'Анастасия Болбат', 'иллюстратор' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Анастасия Болбат' AND job='иллюстратор');
INSERT INTO "Workers" (name, job) SELECT 'Ольга Осипова', 'дизайнер' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Ольга Осипова' AND job='дизайнер');
INSERT INTO "Workers" (name, job) SELECT 'Артём Артамонов', 'дизайнер' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Артём Артамонов' AND job='дизайнер');
INSERT INTO "Workers" (name, job) SELECT 'Виктория Юшина', 'верстальщик' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Виктория Юшина' AND job='верстальщик');
INSERT INTO "Workers" (name, job) SELECT 'Илья Черкасов', 'веб-мастер' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Илья Черкасов' AND job='веб-мастер');
INSERT INTO "Workers" (name, job) SELECT 'Александра Вакулинская', 'продюсер' WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name='Александра Вакулинская' AND job='продюсер');

-- EbookWorkers ← (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1)
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Ирина Курако' AND job='редактор' ORDER BY id LIMIT 1), 0 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Ася Шарамаева' AND job='редактор' ORDER BY id LIMIT 1), 1 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Глеб Кашеваров' AND job='редактор' ORDER BY id LIMIT 1), 2 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Александра Яковлева' AND job='редактор' ORDER BY id LIMIT 1), 3 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Наталья Атряхайлова' AND job='редактор' ORDER BY id LIMIT 1), 4 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Вера Вересиянова' AND job='корректор' ORDER BY id LIMIT 1), 5 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Александра Каменёк' AND job='корректор' ORDER BY id LIMIT 1), 6 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Катерина Гребенщикова' AND job='корректор' ORDER BY id LIMIT 1), 7 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Софья Попова' AND job='корректор' ORDER BY id LIMIT 1), 8 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Полина Смолякова' AND job='корректор' ORDER BY id LIMIT 1), 9 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Лена Солнцева' AND job='иллюстратор' ORDER BY id LIMIT 1), 10 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Маргарита Царева' AND job='иллюстратор' ORDER BY id LIMIT 1), 11 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Екатерина Ковалевская' AND job='иллюстратор' ORDER BY id LIMIT 1), 12 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Екатерина Кравченко' AND job='дизайнер' ORDER BY id LIMIT 1), 13 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Диана Гильманова' AND job='верстальщик' ORDER BY id LIMIT 1), 14 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Анастасия Лукьянова' AND job='веб-мастер' ORDER BY id LIMIT 1), 15 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-6') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Дарья Драхлер' AND job='продюсер' ORDER BY id LIMIT 1), 16 ON CONFLICT (ebook_id, worker_id) DO NOTHING;

-- PrintedBookWorkers ← (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1)
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Анна Волкова' AND job='редактор' ORDER BY id LIMIT 1), 0 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Никита Барков' AND job='редактор' ORDER BY id LIMIT 1), 1 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Ася Шарамаева' AND job='редактор' ORDER BY id LIMIT 1), 2 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Глеб Кашеваров' AND job='редактор' ORDER BY id LIMIT 1), 3 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Ирина Курако' AND job='редактор' ORDER BY id LIMIT 1), 4 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Софья Попова' AND job='редактор' ORDER BY id LIMIT 1), 5 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Вера Вересиянова' AND job='корректор' ORDER BY id LIMIT 1), 6 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Нелли Реук' AND job='корректор' ORDER BY id LIMIT 1), 7 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Анастасия Давыдова' AND job='корректор' ORDER BY id LIMIT 1), 8 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Татьяна Максимова' AND job='корректор' ORDER BY id LIMIT 1), 9 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Катерина Гребенщикова' AND job='корректор' ORDER BY id LIMIT 1), 10 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Анастасия Автухова' AND job='корректор' ORDER BY id LIMIT 1), 11 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Александра Крученкова' AND job='корректор' ORDER BY id LIMIT 1), 12 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Ксения Шунькина' AND job='корректор' ORDER BY id LIMIT 1), 13 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Лена Солнцева' AND job='иллюстратор' ORDER BY id LIMIT 1), 14 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Екатерина Ковалевская' AND job='иллюстратор' ORDER BY id LIMIT 1), 15 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Кладбище Джо' AND job='иллюстратор' ORDER BY id LIMIT 1), 16 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Екатерина Апенько' AND job='иллюстратор' ORDER BY id LIMIT 1), 17 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Анастасия Болбат' AND job='иллюстратор' ORDER BY id LIMIT 1), 18 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Ольга Осипова' AND job='дизайнер' ORDER BY id LIMIT 1), 19 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Артём Артамонов' AND job='дизайнер' ORDER BY id LIMIT 1), 20 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Виктория Юшина' AND job='верстальщик' ORDER BY id LIMIT 1), 21 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Диана Гильманова' AND job='верстальщик' ORDER BY id LIMIT 1), 22 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Илья Черкасов' AND job='веб-мастер' ORDER BY id LIMIT 1), 23 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order) SELECT (SELECT id FROM "PrintedBooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Александра Вакулинская' AND job='продюсер' ORDER BY id LIMIT 1), 24 ON CONFLICT (printed_book_id, worker_id) DO NOTHING;

-- EbookWorkers ← (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1)
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Анна Волкова' AND job='редактор' ORDER BY id LIMIT 1), 0 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Никита Барков' AND job='редактор' ORDER BY id LIMIT 1), 1 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Ася Шарамаева' AND job='редактор' ORDER BY id LIMIT 1), 2 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Глеб Кашеваров' AND job='редактор' ORDER BY id LIMIT 1), 3 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Ирина Курако' AND job='редактор' ORDER BY id LIMIT 1), 4 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Софья Попова' AND job='редактор' ORDER BY id LIMIT 1), 5 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Вера Вересиянова' AND job='корректор' ORDER BY id LIMIT 1), 6 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Нелли Реук' AND job='корректор' ORDER BY id LIMIT 1), 7 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Анастасия Давыдова' AND job='корректор' ORDER BY id LIMIT 1), 8 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Татьяна Максимова' AND job='корректор' ORDER BY id LIMIT 1), 9 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Катерина Гребенщикова' AND job='корректор' ORDER BY id LIMIT 1), 10 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Анастасия Автухова' AND job='корректор' ORDER BY id LIMIT 1), 11 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Александра Крученкова' AND job='корректор' ORDER BY id LIMIT 1), 12 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Ксения Шунькина' AND job='корректор' ORDER BY id LIMIT 1), 13 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Лена Солнцева' AND job='иллюстратор' ORDER BY id LIMIT 1), 14 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Екатерина Ковалевская' AND job='иллюстратор' ORDER BY id LIMIT 1), 15 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Кладбище Джо' AND job='иллюстратор' ORDER BY id LIMIT 1), 16 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Екатерина Апенько' AND job='иллюстратор' ORDER BY id LIMIT 1), 17 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Анастасия Болбат' AND job='иллюстратор' ORDER BY id LIMIT 1), 18 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Ольга Осипова' AND job='дизайнер' ORDER BY id LIMIT 1), 19 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Артём Артамонов' AND job='дизайнер' ORDER BY id LIMIT 1), 20 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Виктория Юшина' AND job='верстальщик' ORDER BY id LIMIT 1), 21 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Диана Гильманова' AND job='верстальщик' ORDER BY id LIMIT 1), 22 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Илья Черкасов' AND job='веб-мастер' ORDER BY id LIMIT 1), 23 ON CONFLICT (ebook_id, worker_id) DO NOTHING;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order) SELECT (SELECT id FROM "Ebooks" WHERE title_id=(SELECT id FROM "Titles" WHERE slug='mrd-5') LIMIT 1), (SELECT id FROM "Workers" WHERE name='Александра Вакулинская' AND job='продюсер' ORDER BY id LIMIT 1), 24 ON CONFLICT (ebook_id, worker_id) DO NOTHING;

COMMIT;
