-- МРД №2 (2021) — issue of «Могучий Русский Динозавр».
-- Generated by scripts/extract-mrd-issues.mjs. Re-runnable.

BEGIN;

INSERT INTO "Periodicals" (name, slug, sort_order)
SELECT 'Могучий Русский Динозавр', 'moguchij-russkij-dinozavr', 0
WHERE NOT EXISTS (SELECT 1 FROM "Periodicals" WHERE slug = 'moguchij-russkij-dinozavr');

SELECT setval('"Titles_id_seq"', COALESCE((SELECT MAX(id) FROM "Titles"), 0) + 1, false);
SELECT setval('"Ebooks_id_seq"', COALESCE((SELECT MAX(id) FROM "Ebooks"), 0) + 1, false);
SELECT setval('"PrintedBooks_id_seq"', COALESCE((SELECT MAX(id) FROM "PrintedBooks"), 0) + 1, false);
SELECT setval('"Titles_Authors_id_seq"', COALESCE((SELECT MAX(id) FROM "Titles_Authors"), 0) + 1, false);

INSERT INTO "Titles" (name, slug, cover, cover_blur, is_compilation, age_restriction, lit_form, first_release, status, periodical_id, volume_number, volume_year)
SELECT 'МРД2', 'mrd-2', 'mrd-2.jpg', 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAQQF/8QAHRAAAgICAwEAAAAAAAAAAAAAAQIDEQAEEhMhUf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFREBAQAAAAAAAAAAAAAAAAAAACH/2gAMAwEAAhEDEQA/AMnU1U2NcvzRGF0pBJaheSEWSeIxi2ZoVkjR6S/RX3DuryslH//Z', true, 18, 'ежегодник', '2021', 'published',
       (SELECT id FROM "Periodicals" WHERE slug = 'moguchij-russkij-dinozavr'), 2, '2021'
WHERE NOT EXISTS (SELECT 1 FROM "Titles" WHERE slug = 'mrd-2');

UPDATE "Titles" SET
  name = 'МРД2',
  cover = 'mrd-2.jpg',
  cover_blur = 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAQQF/8QAHRAAAgICAwEAAAAAAAAAAAAAAQIDEQAEEhMhUf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFREBAQAAAAAAAAAAAAAAAAAAACH/2gAMAwEAAhEDEQA/AMnU1U2NcvzRGF0pBJaheSEWSeIxi2ZoVkjR6S/RX3DuryslH//Z',
  is_compilation = true,
  age_restriction = 18,
  lit_form = 'ежегодник',
  first_release = '2021',
  status = 'published',
  periodical_id = (SELECT id FROM "Periodicals" WHERE slug = 'moguchij-russkij-dinozavr'),
  volume_number = 2,
  volume_year = '2021'
WHERE slug = 'mrd-2';

DELETE FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2');
DELETE FROM "CardBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2');
DELETE FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2');

INSERT INTO "Ebooks" (title_id, price, is_published, publish_date, release_date, formats, character_count, file_path)
SELECT (SELECT id FROM "Titles" WHERE slug = 'mrd-2'), 0, true, '2021-12-30', '2021-12-30',
  ARRAY['PDF'], NULL, 'ebook/mrd-2.pdf';

UPDATE "Articles" SET title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2') WHERE slug LIKE 'mrd2-%';

DELETE FROM "Titles_Authors" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2');
INSERT INTO "Titles_Authors" (title_id, author_id)
SELECT DISTINCT a.title_id, a.author_id
FROM "Articles" a
WHERE a.slug LIKE 'mrd2-%' AND a.title_id IS NOT NULL AND a.author_id IS NOT NULL;

COMMIT;
