-- МРД №4 (2023) — issue of «Могучий Русский Динозавр».
-- Generated by scripts/extract-mrd-issues.mjs. Re-runnable.

BEGIN;

INSERT INTO "Periodicals" (name, slug, sort_order)
SELECT 'Могучий Русский Динозавр', 'moguchij-russkij-dinozavr', 0
WHERE NOT EXISTS (SELECT 1 FROM "Periodicals" WHERE slug = 'moguchij-russkij-dinozavr');

SELECT setval('"Titles_id_seq"', COALESCE((SELECT MAX(id) FROM "Titles"), 0) + 1, false);
SELECT setval('"Ebooks_id_seq"', COALESCE((SELECT MAX(id) FROM "Ebooks"), 0) + 1, false);
SELECT setval('"PrintedBooks_id_seq"', COALESCE((SELECT MAX(id) FROM "PrintedBooks"), 0) + 1, false);
SELECT setval('"Titles_Authors_id_seq"', COALESCE((SELECT MAX(id) FROM "Titles_Authors"), 0) + 1, false);

INSERT INTO "Titles" (name, slug, cover, cover_blur, is_compilation, age_restriction, lit_form, first_release, status, periodical_id, volume_number, volume_year)
SELECT 'МРД4', 'mrd-4', 'mrd-4.jpg', 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAPAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAIBAAAgEEAgMBAAAAAAAAAAAAAQIDAAQSIRFRMTJBYf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAGBEBAQADAAAAAAAAAAAAAAAAAQACEUH/2gAMAwEAAhEDEQA/AND3igy+zBW4yHgb4GqskkBRTiTod0ZcWjTSTMWGTkFGPz8IpGExJCiNEGZVAJ7o01rjwv/Z', true, 18, 'ежегодник', '2023', 'published',
       (SELECT id FROM "Periodicals" WHERE slug = 'moguchij-russkij-dinozavr'), 4, '2023'
WHERE NOT EXISTS (SELECT 1 FROM "Titles" WHERE slug = 'mrd-4');

UPDATE "Titles" SET
  name = 'МРД4',
  cover = 'mrd-4.jpg',
  cover_blur = 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAPAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAIBAAAgEEAgMBAAAAAAAAAAAAAQIDAAQSIRFRMTJBYf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAGBEBAQADAAAAAAAAAAAAAAAAAQACEUH/2gAMAwEAAhEDEQA/AND3igy+zBW4yHgb4GqskkBRTiTod0ZcWjTSTMWGTkFGPz8IpGExJCiNEGZVAJ7o01rjwv/Z',
  is_compilation = true,
  age_restriction = 18,
  lit_form = 'ежегодник',
  first_release = '2023',
  status = 'published',
  periodical_id = (SELECT id FROM "Periodicals" WHERE slug = 'moguchij-russkij-dinozavr'),
  volume_number = 4,
  volume_year = '2023'
WHERE slug = 'mrd-4';

DELETE FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4');
DELETE FROM "CardBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4');
DELETE FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4');

INSERT INTO "Ebooks" (title_id, price, is_published, publish_date, release_date, formats, character_count, file_path)
SELECT (SELECT id FROM "Titles" WHERE slug = 'mrd-4'), 0, true, '2023-12-31', '2023-12-31',
  ARRAY['FB2', 'EPUB', 'PDF'], 189000, 'ebook/mrd-4.epub';

UPDATE "Articles" SET title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') WHERE slug LIKE 'mrd4-%';

DELETE FROM "Titles_Authors" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4');
INSERT INTO "Titles_Authors" (title_id, author_id)
SELECT DISTINCT a.title_id, a.author_id
FROM "Articles" a
WHERE a.slug LIKE 'mrd4-%' AND a.title_id IS NOT NULL AND a.author_id IS NOT NULL;

COMMIT;
