-- МРД №5 (2024) — issue of «Могучий Русский Динозавр».
-- Generated by scripts/extract-mrd-issues.mjs. Re-runnable.

BEGIN;

INSERT INTO "Periodicals" (name, slug, sort_order)
SELECT 'Могучий Русский Динозавр', 'moguchij-russkij-dinozavr', 0
WHERE NOT EXISTS (SELECT 1 FROM "Periodicals" WHERE slug = 'moguchij-russkij-dinozavr');

SELECT setval('"Titles_id_seq"', COALESCE((SELECT MAX(id) FROM "Titles"), 0) + 1, false);
SELECT setval('"Ebooks_id_seq"', COALESCE((SELECT MAX(id) FROM "Ebooks"), 0) + 1, false);
SELECT setval('"PrintedBooks_id_seq"', COALESCE((SELECT MAX(id) FROM "PrintedBooks"), 0) + 1, false);
SELECT setval('"Titles_Authors_id_seq"', COALESCE((SELECT MAX(id) FROM "Titles_Authors"), 0) + 1, false);

INSERT INTO "Titles" (name, slug, cover, cover_blur, is_compilation, age_restriction, lit_form, first_release, status, periodical_id, volume_number, volume_year)
SELECT 'МРД5', 'mrd-5', 'mrd-5.jpg', 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAPAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAIhAAAgEDBAIDAAAAAAAAAAAAAQIDAAQxBRESISNBQrHR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AK32oTK0qSTiJA/EDfds4697eiaajukMakccDMbUJqlrbm6jEKCFgRK5X5d/f7WdtXvwxCzJx368YxQf/9k=', true, 18, 'ежегодник', '2024', 'published',
       (SELECT id FROM "Periodicals" WHERE slug = 'moguchij-russkij-dinozavr'), 5, '2024'
WHERE NOT EXISTS (SELECT 1 FROM "Titles" WHERE slug = 'mrd-5');

UPDATE "Titles" SET
  name = 'МРД5',
  cover = 'mrd-5.jpg',
  cover_blur = 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAPAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAIhAAAgEDBAIDAAAAAAAAAAAAAQIDAAQxBRESISNBQrHR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AK32oTK0qSTiJA/EDfds4697eiaajukMakccDMbUJqlrbm6jEKCFgRK5X5d/f7WdtXvwxCzJx368YxQf/9k=',
  is_compilation = true,
  age_restriction = 18,
  lit_form = 'ежегодник',
  first_release = '2024',
  status = 'published',
  periodical_id = (SELECT id FROM "Periodicals" WHERE slug = 'moguchij-russkij-dinozavr'),
  volume_number = 5,
  volume_year = '2024'
WHERE slug = 'mrd-5';

DELETE FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5');
DELETE FROM "CardBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5');
DELETE FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5');

INSERT INTO "PrintedBooks"
  (title_id, price, is_published, publish_date, release_date, format, page_count, paper, cover_material, binding, illustrations)
SELECT (SELECT id FROM "Titles" WHERE slug = 'mrd-5'), 700, true, '2025-01-01', '2024-10-15',
  '210×297 мм', 204, 'офсетная, 80 гр/кв.м', 'мелованная, 250 гр/кв.м, матовое ламинирование', 'КБС, термопак поэкземплярно', 'чёрно-белые';

INSERT INTO "Ebooks" (title_id, price, is_published, publish_date, release_date, formats, character_count, file_path)
SELECT (SELECT id FROM "Titles" WHERE slug = 'mrd-5'), 0, true, '2025-01-01', '2024-10-15',
  ARRAY['FB2', 'EPUB', 'PDF'], 269000, 'ebook/mrd-5.epub';

UPDATE "Articles" SET title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') WHERE slug LIKE 'mrd5-%';

DELETE FROM "Titles_Authors" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5');
INSERT INTO "Titles_Authors" (title_id, author_id)
SELECT DISTINCT a.title_id, a.author_id
FROM "Articles" a
WHERE a.slug LIKE 'mrd5-%' AND a.title_id IS NOT NULL AND a.author_id IS NOT NULL;

COMMIT;
