-- Generated by scripts/scrape-contexts.mjs from chtivo.spb.ru
-- Do not edit by hand; re-run the script to regenerate.

DELETE FROM "BookContexts";
ALTER SEQUENCE "BookContexts_id_seq" RESTART WITH 1;

-- amystis
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'amystis'), 'Что мы вообще знаем об Олеге Новокщёнове', 'Что мы с вами вообще знаем об Олеге Новокщёнове? Вот то немногое, что нам удалось выяснить из переписки с ним и открытых источников.', 'https://vk.com/@russiantrex-chto-my-voobsche-znaem-ob-avtore-amystis-olege-novokschenove', 0);

-- doctor-sax
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'doctor-sax'), 'Доктор Сакс и Великий Мировой Змей: забытый опус Керуака | Катерина де Леон', 'Очерк Катерины де Леон в переводе Андрея Щетникова об искренней и пророческой книге Джека Керуака «Доктор Сакс» — романе, который не так-то просто разгадать между строк битнической прозы.', 'https://vk.com/@russiantrex-doktor-saks-i-velikii-mirovoi-zmei-zabytyi-opus-keruaka-katr', 0);

-- frieda-and-gitta
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'frieda-and-gitta'), '«Пиво, минет и — расслабьтесь». Первое интервью неизвестного героя бит-поколения Эриха фон Неффа', 'Материал Сергея Дедовича, посвящённый автору и опубликованный в журнале Дискурс.', 'https://6243612d5980520009703948-discours.netlify.app/articles/culture/pivo-minet-i-rasslabtes-pervoe-intervyu-neizvestnogo-geroya-bit-pokoleniya-eriha-fon-neffa', 0),
  ((SELECT id FROM "Titles" WHERE slug = 'frieda-and-gitta'), 'Что мы вообще знаем об Эрихе фон Неффе', 'Что мы с вами вообще знаем об Эрихе фон Неффе? Вот то немногое, что нам удалось выяснить из переписки с ним и открытых источников.', 'https://dzen.ru/media/russiandino/chto-my-voobsce-znaem-ob-avtore-prostitutok-na-obochine-5cf7a78c2d133400afd9b2a4', 1);

-- irokez
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'irokez'), '«Ирокез» Алексея Колесникова | Год Литературы', 'На сайте Год Литературы опубликовали рассказ «Итака» из сборника «Ирокез» Алексея Колесникова, сопроводив его рецензией от Андрея Мягкова.', 'https://godliteratury.ru/articles/2022/05/19/irokez-alekseia-kolesnikova', 0),
  ((SELECT id FROM "Titles" WHERE slug = 'irokez'), 'Интервью с Алексеем Колесниковым', 'В День рождения А.С. Пушкина на Красной площади вручали премии молодым авторам, среди которых в этом году был и Алексей Колёсников: его сборник «Ирокез» оценили по достоинству, отметив 3-м почётным местом. Мы пообщались с Алексеем о премии и о его творчестве.', 'https://vk.com/@ichtivo-intervu-s-alekseem-kolesnikovym', 1);

-- kubok-voiny-i-tanca
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'kubok-voiny-i-tanca'), 'Правила смерти Оганеса Мартиросяна', 'В рубрике «Правила смерти» мы расспрашиваем на эту тему замечательных людей нашего времени. О своих правилах смерти рассказывает драматург, поэт, писатель Оганес Мартиросян.', 'https://vk.com/@russiantrex-pravila-smerti-oganesa-martirosyana', 0),
  ((SELECT id FROM "Titles" WHERE slug = 'kubok-voiny-i-tanca'), 'Что мы вообще знаем об Оганесе Мартиросяне', 'Что мы с вами вообще знаем об Оганесе Мартиросяне? Вот то немногое, что нам удалось выяснить из переписки с ним и открытых источников.', 'https://dzen.ru/media/russiandino/chto-my-voobsce-znaem-ob-avtore-kubka-voiny-i-tanca-5da3310d6f5f6f00ad962087', 1);

-- overdrive
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'overdrive'), 'Антироман «Овердрайв» — секс, наркотики, рок-н-ролл, иногда в другом порядке | журнал ROCKWEEK', 'Читайте первый большой материал об «Овердрайве» Сергея Иннера в журнале ROCKWEEK. Автор текста — Виктория Травникова.', 'https://rockweek.ru/antiroman-overdrive/', 0),
  ((SELECT id FROM "Titles" WHERE slug = 'overdrive'), 'Рецензия на роман Сергея Иннера «Овердрайв»', 'Читайте рецензию автора «Янгспейс» и писателя Василия Вялого на роман Сергея Иннера — «Овердрайв».', 'https://youngspace.ru/culture/retsenziya-na-roman-sergeya-innera-overdrajv', 1),
  ((SELECT id FROM "Titles" WHERE slug = 'overdrive'), 'Родина Иннера', 'Спецпроект Русского Динозавра, журналистское расследование, проведённое в местах рождения и становления Сергея Иннера — городе Таганроге Ростовской области.', 'https://vk.com/@rocknword-rodina-innera', 2);

-- podzemnie
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'podzemnie'), '«Ещё одна пропитая любовь». Религия битников и алкогольный солипсизм в романе Керуака «Подземные»', 'Материал Николая Старообрядцева о «Подземных» Джека Керуака в журнале Дискурс.', 'https://discours.io/articles/culture/esch-odna-propitaya-lyubov-religiya-bitnikov-i-alkogolnyy-solipsizm-v-romane-keruaka-podzemnye', 0);

-- pozhninoch
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'pozhninoch'), 'Родина Иннера', 'Спецпроект Русского Динозавра, журналистское расследование, проведённое в местах рождения и становления Сергея Иннера — городе Таганроге Ростовской области.', 'https://vk.com/@rocknword-rodina-innera', 0);

-- prostitutes
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'prostitutes'), 'Что мы вообще знаем об Эрихе фон Неффе?', 'Что мы с вами вообще знаем об Эрихе фон Неффе? Вот то немногое, что нам удалось выяснить из переписки с ним и открытых источников.', 'https://dzen.ru/media/russiandino/chto-my-voobsce-znaem-ob-avtore-prostitutok-na-obochine-5cf7a78c2d133400afd9b2a4', 0),
  ((SELECT id FROM "Titles" WHERE slug = 'prostitutes'), 'Эксперимент с восприятием. О книге «Проститутки на обочине» Эриха фон Неффа', 'Недавно наши редакторы получили рукопись, которая увлекла их в удивительный эксперимент на тему зависимости восприятия произведения от восприятия автора. Эксперимент завершён, и мы предлагаем вам ознакомиться с этой любопытной историей.', 'https://dzen.ru/media/russiandino/eksperiment-s-vospriiatiem-o-knige-prostitutki-na-obochine-eriha-fon-neffa-5cd7f95b02da9d00b3fc2c36?utm_referer=away.vk.com', 1),
  ((SELECT id FROM "Titles" WHERE slug = 'prostitutes'), 'Как мы «Проституток на обочине» Эриха фон Неффа издавали', 'Книга «Проститутки на обочине» американского писателя Эриха фон Неффа вышла 10 июня в издательстве Чтиво. Возможно, вы уже читали наш материал об истории знакомства с автором. Этот проект был несказанно важен для Чтива: первая книга зарубежного автора, притом довольно известного, пусть и на другом конце Земли, и даже состоявшего в переписке с Алленом Гинзбергом(!). Стоит ли говорить, как мы переживали. Пожалуй, лучше поговорить о том, как мы издавали.', 'https://dzen.ru/media/russiandino/kak-my-prostitutok-na-obochine-eriha-fon-neffa-izdavali-5d0104fb582ec400ab67f65e', 2),
  ((SELECT id FROM "Titles" WHERE slug = 'prostitutes'), 'Другая сторона дороги | Любовь Волдинер', 'Любовь Волдинер о «Проститутках на обочине» Эриха фон Неффа.', 'https://dzen.ru/media/russiandino/drugaia-storona-dorogi-na-knigu-prostituki-na-obochine-eriha-fon-neffa-liubov-voldiner-5e860cbcbb31c2679c6eb75a', 3),
  ((SELECT id FROM "Titles" WHERE slug = 'prostitutes'), 'Сексуально-политический трактат Эриха фон Неффа | Николай Старообрядцев', '10 июня 2019-ого года в издательстве Чтиво вышло первое русскоязычное издание книги «Проститутки на обочине» калифорнийского писателя, философа и портового докера Эриха фон Неффа. Критика петербургского автора Николая Старообрядцева не заставила себя долго ждать.', 'https://vk.com/@russiantrex-seksualno-politicheskii-traktat-eriha-fon-neffa-nikolai-star', 4);

-- rossijskoe-vremja
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'rossijskoe-vremja'), 'Правила смерти Георгия Панкратова', 'В рубрике «Правила смерти» мы расспрашиваем на эту тему замечательных людей нашего времени. О своих правилах смерти рассказывает автор книги «Российское время» Георгий Панкратов.', 'https://vk.com/@russiantrex-pravila-smerti-georgiya-pankratova', 0),
  ((SELECT id FROM "Titles" WHERE slug = 'rossijskoe-vremja'), 'Интервью с Георгием Панкратовым | журнал «Янгспейс»', 'Журнал «Янгспейс» пообщался с автором о новой книге, литературном настоящем в социальных сетях и узнал, как писателю пробиться к читателю.', 'https://youngspace.ru/culture/intervyu-s-georgiem-pankratovym', 1),
  ((SELECT id FROM "Titles" WHERE slug = 'rossijskoe-vremja'), 'Российское время | журнал «Знамя»', 'Читайте рецензию Станислава Секретова на «Российское время» Георгия Панкратова в журнале «Знамя».', 'https://znamlit.ru/publication.php?id=7731', 2);

-- slava
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'slava'), 'А вот и Слава! Интервью с Вячеславом Немировым', 'Мы решили узнать автора сборника рассказов «А где же Слава?» поближе и спросили Вячеслава о любимых писателях, творческом процессе и литературных планах. Вот что получилось.', 'https://vk.com/@ichtivo-intervu-s-vyacheslavom-nemirovym', 0),
  ((SELECT id FROM "Titles" WHERE slug = 'slava'), 'Правила смерти Вячеслава Немирова', 'В рубрике «Правила смерти» мы расспрашиваем на эту тему замечательных людей нашего времени. О своих правилах смерти рассказывает писатель и поэт Вячеслав Немиров.', 'https://vk.com/@ichtivo-pravila-smerti-vyacheslava-nemirova', 1);

-- v-doroge
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'v-doroge'), 'Интервью с переводчиком Андреем Щетниковым | Журнал Дискурс', '«"В дороге" — это гимн Америке: это и "легендарная" Америка прошлого, и одновременно Америка сегодняшняя. Взаимоотношения со временем сложные, и отношения со страной тоже сложные, но он живёт в ней и хочет о ней рассказать».', 'https://discours.io/articles/culture/ya-ves-ih-put-prosh-l-v-gugl-kartah-perevodchik-bitnikov-o-revolyutsii-soznaniya-buntarstve-i-manifeste-bit-pokoleniya', 0),
  ((SELECT id FROM "Titles" WHERE slug = 'v-doroge'), 'On Kerouac | Николай Старообрядцев', 'Летом 2020-ого года в свет вышел новый перевод легендарного романа «On the Road» Джека Керуака в переводе специалиста по зарубежной поэзии Андрея Щетникова (г. Новосибирск). Специальным гостем презентации издания в баре «Parabellum» в Санкт-Петербурге стал писатель и философ Николай Старообрядцев. Его спонтанная лекция о романе «В дороге» и феномене битников вообще пришлась аудитории по душе, и мы попросили Николая создать её письменную версию, на что он любезно согласился.', 'https://vk.com/@ichtivo-on-kerouac-nikolai-staroobryadcev', 1);

-- white-flower
INSERT INTO "BookContexts" (title_id, heading, body, url, sort_order)
VALUES
  ((SELECT id FROM "Titles" WHERE slug = 'white-flower'), 'Правила смерти Николая Старообрядцева', 'В рубрике «Правила смерти» мы расспрашиваем на эту тему замечательных людей нашего времени. О своих правилах смерти рассказывает петербургский писатель и философ Николай Старообрядцев.', 'https://vk.com/@ichtivo-pravila-smerti-nikolaya-staroobryadceva', 0),
  ((SELECT id FROM "Titles" WHERE slug = 'white-flower'), '«Работаю как исследователь»: интервью с Николаем Старообрядцевым | Журнал МОСТ', '«Начнем с простого – талант или гений?». Интервью Николая Старообрядцева журналу МОСТ.', 'https://mostmag.ru/rabotaju-kak-issledovatel-intervju-s-nikolaem-staroobrjadcevym/', 1);
