-- МРД №6 (2026) — issue of «Могучий Русский Динозавр».
-- Generated by scripts/extract-mrd-issues.mjs. Re-runnable.

BEGIN;

INSERT INTO "Periodicals" (name, slug, sort_order)
SELECT 'Могучий Русский Динозавр', 'moguchij-russkij-dinozavr', 0
WHERE NOT EXISTS (SELECT 1 FROM "Periodicals" WHERE slug = 'moguchij-russkij-dinozavr');

SELECT setval('"Titles_id_seq"', COALESCE((SELECT MAX(id) FROM "Titles"), 0) + 1, false);
SELECT setval('"Ebooks_id_seq"', COALESCE((SELECT MAX(id) FROM "Ebooks"), 0) + 1, false);
SELECT setval('"PrintedBooks_id_seq"', COALESCE((SELECT MAX(id) FROM "PrintedBooks"), 0) + 1, false);
SELECT setval('"Titles_Authors_id_seq"', COALESCE((SELECT MAX(id) FROM "Titles_Authors"), 0) + 1, false);

-- Migrate the legacy МРД6 title slug (it equalled the periodical slug) to mrd-6.
UPDATE "Titles" SET slug = 'mrd-6' WHERE slug = 'moguchij-russkij-dinozavr';

INSERT INTO "Titles" (name, slug, cover, cover_blur, is_compilation, age_restriction, lit_form, first_release, status, periodical_id, volume_number, volume_year)
SELECT 'МРД6', 'mrd-6', 'mrd-6.jpg', 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAPAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAID/8QAHRAAAgIDAAMAAAAAAAAAAAAAAQIDIQAEEUFRgf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAZEQACAwEAAAAAAAAAAAAAAAABAgARIQP/2gAMAwEAAhEDEQA/AFRb0BjRUialBoDATTapmkIiUAsaqryIE4pcqKXnQfGaHXk77+4bVeGo6MeeMpaf/9k=', true, 18, 'ежегодник', '2026', 'published',
       (SELECT id FROM "Periodicals" WHERE slug = 'moguchij-russkij-dinozavr'), 6, '2026'
WHERE NOT EXISTS (SELECT 1 FROM "Titles" WHERE slug = 'mrd-6');

UPDATE "Titles" SET
  name = 'МРД6',
  cover = 'mrd-6.jpg',
  cover_blur = 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAPAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAID/8QAHRAAAgIDAAMAAAAAAAAAAAAAAQIDIQAEEUFRgf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAZEQACAwEAAAAAAAAAAAAAAAABAgARIQP/2gAMAwEAAhEDEQA/AFRb0BjRUialBoDATTapmkIiUAsaqryIE4pcqKXnQfGaHXk77+4bVeGo6MeeMpaf/9k=',
  is_compilation = true,
  age_restriction = 18,
  lit_form = 'ежегодник',
  first_release = '2026',
  status = 'published',
  periodical_id = (SELECT id FROM "Periodicals" WHERE slug = 'moguchij-russkij-dinozavr'),
  volume_number = 6,
  volume_year = '2026'
WHERE slug = 'mrd-6';

DELETE FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6');
DELETE FROM "CardBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6');
DELETE FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6');

INSERT INTO "Ebooks" (title_id, price, is_published, publish_date, release_date, formats, character_count, file_path)
SELECT (SELECT id FROM "Titles" WHERE slug = 'mrd-6'), 0, true, '2026-01-20', '2026-01-20',
  ARRAY['FB2', 'EPUB'], 280000, 'ebook/mrd-6.epub';

UPDATE "Articles" SET title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') WHERE slug LIKE 'mrd6-%';

DELETE FROM "Titles_Authors" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6');
INSERT INTO "Titles_Authors" (title_id, author_id)
SELECT DISTINCT a.title_id, a.author_id
FROM "Articles" a
WHERE a.slug LIKE 'mrd6-%' AND a.title_id IS NOT NULL AND a.author_id IS NOT NULL;

COMMIT;
