-- Production credits for МРД issues. Generated by scripts/extract-mrd-issues.mjs.
-- Re-runnable. Inserts Workers by name+job and links them to issue editions.

BEGIN;

SELECT setval('"Workers_id_seq"', COALESCE((SELECT MAX(id) FROM "Workers"), 0) + 1, false);
SELECT setval('"EbookWorkers_id_seq"', COALESCE((SELECT MAX(id) FROM "EbookWorkers"), 0) + 1, false);
SELECT setval('"PrintedBookWorkers_id_seq"', COALESCE((SELECT MAX(id) FROM "PrintedBookWorkers"), 0) + 1, false);

INSERT INTO "Workers" (name, job)
SELECT 'Екатерина Яковлева', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Екатерина Яковлева' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Наталья Коваленко', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Наталья Коваленко' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Дмитрий Козлов', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Дмитрий Козлов' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Лена Солнцева', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Лена Солнцева' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Ольга Тамкович', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Ольга Тамкович' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Александра Давидович', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Александра Давидович' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Мария Давидович', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Мария Давидович' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Илья Смирнов', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Илья Смирнов' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Александра Яшаркина', 'верстальщик'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Александра Яшаркина' AND job = 'верстальщик');

INSERT INTO "Workers" (name, job)
SELECT 'Сергей Дедович', 'редактор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Сергей Дедович' AND job = 'редактор');

INSERT INTO "Workers" (name, job)
SELECT 'Максим Димов', 'веб-мастер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Максим Димов' AND job = 'веб-мастер');

INSERT INTO "Workers" (name, job)
SELECT 'Серафим Лоза', 'веб-мастер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Серафим Лоза' AND job = 'веб-мастер');

INSERT INTO "Workers" (name, job)
SELECT 'Катерина Курносова', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Катерина Курносова' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Ксения Харина', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Ксения Харина' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Елена Солнцева', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Елена Солнцева' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Анна Мухина', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Анна Мухина' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Даниил Румянцев', 'дизайнер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Даниил Румянцев' AND job = 'дизайнер');

INSERT INTO "Workers" (name, job)
SELECT 'Катерина Видяскина', 'дизайнер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Катерина Видяскина' AND job = 'дизайнер');

INSERT INTO "Workers" (name, job)
SELECT 'Леон Меликьянц', 'верстальщик'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Леон Меликьянц' AND job = 'верстальщик');

INSERT INTO "Workers" (name, job)
SELECT 'Анастасия Ворожейкина', 'редактор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Анастасия Ворожейкина' AND job = 'редактор');

INSERT INTO "Workers" (name, job)
SELECT 'Александр Лызь', 'веб-мастер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Александр Лызь' AND job = 'веб-мастер');

INSERT INTO "Workers" (name, job)
SELECT 'Полина Шарафутдинова', 'редактор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Полина Шарафутдинова' AND job = 'редактор');

INSERT INTO "Workers" (name, job)
SELECT 'Анна Волкова', 'редактор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Анна Волкова' AND job = 'редактор');

INSERT INTO "Workers" (name, job)
SELECT 'Никита Барков', 'редактор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Никита Барков' AND job = 'редактор');

INSERT INTO "Workers" (name, job)
SELECT 'Катерина Гребенщикова', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Катерина Гребенщикова' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'Екатерина Ковалевская', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Екатерина Ковалевская' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Горыныч', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Горыныч' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Алексей Капустяк', 'верстальщик'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Алексей Капустяк' AND job = 'верстальщик');

INSERT INTO "Workers" (name, job)
SELECT 'Диана Гильманова', 'продюсер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Диана Гильманова' AND job = 'продюсер');

INSERT INTO "Workers" (name, job)
SELECT 'Катерина Гребенщикова', 'редактор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Катерина Гребенщикова' AND job = 'редактор');

INSERT INTO "Workers" (name, job)
SELECT 'Ася Шарамаева', 'редактор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Ася Шарамаева' AND job = 'редактор');

INSERT INTO "Workers" (name, job)
SELECT 'Дарья Ягрова', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Дарья Ягрова' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'Татьяна Чикичева', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Татьяна Чикичева' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'Вера Вересиянова', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Вера Вересиянова' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'Нелли Реук', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Нелли Реук' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'daha amelina', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'daha amelina' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Юлия Микуша', 'дизайнер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Юлия Микуша' AND job = 'дизайнер');

INSERT INTO "Workers" (name, job)
SELECT 'Артём Артамонов', 'дизайнер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Артём Артамонов' AND job = 'дизайнер');

INSERT INTO "Workers" (name, job)
SELECT 'Глеб Кашеваров', 'редактор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Глеб Кашеваров' AND job = 'редактор');

INSERT INTO "Workers" (name, job)
SELECT 'Ирина Курако', 'редактор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Ирина Курако' AND job = 'редактор');

INSERT INTO "Workers" (name, job)
SELECT 'Софья Попова', 'редактор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Софья Попова' AND job = 'редактор');

INSERT INTO "Workers" (name, job)
SELECT 'Анастасия Давыдова', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Анастасия Давыдова' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'Татьяна Максимова', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Татьяна Максимова' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'Анастасия Автухова', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Анастасия Автухова' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'Александра Крученкова', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Александра Крученкова' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'Ксения Шунькина', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Ксения Шунькина' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'Кладбище Джо', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Кладбище Джо' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Екатерина Апенько', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Екатерина Апенько' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Анастасия Болбат', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Анастасия Болбат' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Ольга Осипова', 'дизайнер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Ольга Осипова' AND job = 'дизайнер');

INSERT INTO "Workers" (name, job)
SELECT 'Виктория Юшина', 'верстальщик'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Виктория Юшина' AND job = 'верстальщик');

INSERT INTO "Workers" (name, job)
SELECT 'Диана Гильманова', 'верстальщик'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Диана Гильманова' AND job = 'верстальщик');

INSERT INTO "Workers" (name, job)
SELECT 'Илья Черкасов', 'веб-мастер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Илья Черкасов' AND job = 'веб-мастер');

INSERT INTO "Workers" (name, job)
SELECT 'Александра Вакулинская', 'продюсер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Александра Вакулинская' AND job = 'продюсер');

INSERT INTO "Workers" (name, job)
SELECT 'Александра Яковлева', 'редактор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Александра Яковлева' AND job = 'редактор');

INSERT INTO "Workers" (name, job)
SELECT 'Наталья Атряхайлова', 'редактор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Наталья Атряхайлова' AND job = 'редактор');

INSERT INTO "Workers" (name, job)
SELECT 'Александра Каменёк', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Александра Каменёк' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'Софья Попова', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Софья Попова' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'Полина Смолякова', 'корректор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Полина Смолякова' AND job = 'корректор');

INSERT INTO "Workers" (name, job)
SELECT 'Маргарита Царева', 'иллюстратор'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Маргарита Царева' AND job = 'иллюстратор');

INSERT INTO "Workers" (name, job)
SELECT 'Екатерина Кравченко', 'дизайнер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Екатерина Кравченко' AND job = 'дизайнер');

INSERT INTO "Workers" (name, job)
SELECT 'Анастасия Лукьянова', 'веб-мастер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Анастасия Лукьянова' AND job = 'веб-мастер');

INSERT INTO "Workers" (name, job)
SELECT 'Дарья Драхлер', 'продюсер'
WHERE NOT EXISTS (SELECT 1 FROM "Workers" WHERE name = 'Дарья Драхлер' AND job = 'продюсер');

DELETE FROM "EbookWorkers" WHERE ebook_id IN (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'));
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Екатерина Яковлева' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 0
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Наталья Коваленко' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 1
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Дмитрий Козлов' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 2
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Лена Солнцева' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 3
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ольга Тамкович' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 4
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Александра Давидович' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 5
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Мария Давидович' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 6
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Илья Смирнов' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 7
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Александра Яшаркина' AND job = 'верстальщик' ORDER BY id LIMIT 1), 8
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Сергей Дедович' AND job = 'редактор' ORDER BY id LIMIT 1), 9
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Максим Димов' AND job = 'веб-мастер' ORDER BY id LIMIT 1), 10
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Серафим Лоза' AND job = 'веб-мастер' ORDER BY id LIMIT 1), 11
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-1'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;

DELETE FROM "EbookWorkers" WHERE ebook_id IN (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2'));
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Катерина Курносова' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 0
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ольга Тамкович' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 1
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ксения Харина' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 2
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Елена Солнцева' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 3
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Екатерина Яковлева' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 4
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анна Мухина' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 5
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Даниил Румянцев' AND job = 'дизайнер' ORDER BY id LIMIT 1), 6
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Катерина Видяскина' AND job = 'дизайнер' ORDER BY id LIMIT 1), 7
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Леон Меликьянц' AND job = 'верстальщик' ORDER BY id LIMIT 1), 8
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анастасия Ворожейкина' AND job = 'редактор' ORDER BY id LIMIT 1), 9
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Александр Лызь' AND job = 'веб-мастер' ORDER BY id LIMIT 1), 10
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-2'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;

DELETE FROM "EbookWorkers" WHERE ebook_id IN (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'));
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Полина Шарафутдинова' AND job = 'редактор' ORDER BY id LIMIT 1), 0
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анастасия Ворожейкина' AND job = 'редактор' ORDER BY id LIMIT 1), 1
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анна Волкова' AND job = 'редактор' ORDER BY id LIMIT 1), 2
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Никита Барков' AND job = 'редактор' ORDER BY id LIMIT 1), 3
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Катерина Гребенщикова' AND job = 'корректор' ORDER BY id LIMIT 1), 4
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Екатерина Ковалевская' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 5
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Лена Солнцева' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 6
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ксения Харина' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 7
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ольга Тамкович' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 8
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Горыныч' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 9
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Катерина Видяскина' AND job = 'дизайнер' ORDER BY id LIMIT 1), 10
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Алексей Капустяк' AND job = 'верстальщик' ORDER BY id LIMIT 1), 11
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Диана Гильманова' AND job = 'продюсер' ORDER BY id LIMIT 1), 12
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-3'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;

DELETE FROM "EbookWorkers" WHERE ebook_id IN (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'));
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анна Волкова' AND job = 'редактор' ORDER BY id LIMIT 1), 0
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Катерина Гребенщикова' AND job = 'редактор' ORDER BY id LIMIT 1), 1
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Никита Барков' AND job = 'редактор' ORDER BY id LIMIT 1), 2
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ася Шарамаева' AND job = 'редактор' ORDER BY id LIMIT 1), 3
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Дарья Ягрова' AND job = 'корректор' ORDER BY id LIMIT 1), 4
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Татьяна Чикичева' AND job = 'корректор' ORDER BY id LIMIT 1), 5
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Вера Вересиянова' AND job = 'корректор' ORDER BY id LIMIT 1), 6
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Нелли Реук' AND job = 'корректор' ORDER BY id LIMIT 1), 7
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Елена Солнцева' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 8
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Екатерина Ковалевская' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 9
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ксения Харина' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 10
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'daha amelina' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 11
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Горыныч' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 12
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Юлия Микуша' AND job = 'дизайнер' ORDER BY id LIMIT 1), 13
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Артём Артамонов' AND job = 'дизайнер' ORDER BY id LIMIT 1), 14
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Алексей Капустяк' AND job = 'верстальщик' ORDER BY id LIMIT 1), 15
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Александра Яшаркина' AND job = 'верстальщик' ORDER BY id LIMIT 1), 16
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Диана Гильманова' AND job = 'продюсер' ORDER BY id LIMIT 1), 17
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-4'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;

DELETE FROM "EbookWorkers" WHERE ebook_id IN (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'));
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анна Волкова' AND job = 'редактор' ORDER BY id LIMIT 1), 0
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Никита Барков' AND job = 'редактор' ORDER BY id LIMIT 1), 1
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ася Шарамаева' AND job = 'редактор' ORDER BY id LIMIT 1), 2
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Глеб Кашеваров' AND job = 'редактор' ORDER BY id LIMIT 1), 3
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ирина Курако' AND job = 'редактор' ORDER BY id LIMIT 1), 4
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Софья Попова' AND job = 'редактор' ORDER BY id LIMIT 1), 5
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Вера Вересиянова' AND job = 'корректор' ORDER BY id LIMIT 1), 6
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Нелли Реук' AND job = 'корректор' ORDER BY id LIMIT 1), 7
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анастасия Давыдова' AND job = 'корректор' ORDER BY id LIMIT 1), 8
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Татьяна Максимова' AND job = 'корректор' ORDER BY id LIMIT 1), 9
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Катерина Гребенщикова' AND job = 'корректор' ORDER BY id LIMIT 1), 10
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анастасия Автухова' AND job = 'корректор' ORDER BY id LIMIT 1), 11
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Александра Крученкова' AND job = 'корректор' ORDER BY id LIMIT 1), 12
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ксения Шунькина' AND job = 'корректор' ORDER BY id LIMIT 1), 13
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Лена Солнцева' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 14
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Екатерина Ковалевская' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 15
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Кладбище Джо' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 16
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Екатерина Апенько' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 17
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анастасия Болбат' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 18
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ольга Осипова' AND job = 'дизайнер' ORDER BY id LIMIT 1), 19
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Артём Артамонов' AND job = 'дизайнер' ORDER BY id LIMIT 1), 20
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Виктория Юшина' AND job = 'верстальщик' ORDER BY id LIMIT 1), 21
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Диана Гильманова' AND job = 'верстальщик' ORDER BY id LIMIT 1), 22
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Илья Черкасов' AND job = 'веб-мастер' ORDER BY id LIMIT 1), 23
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Александра Вакулинская' AND job = 'продюсер' ORDER BY id LIMIT 1), 24
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;

DELETE FROM "PrintedBookWorkers" WHERE printed_book_id IN (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'));
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анна Волкова' AND job = 'редактор' ORDER BY id LIMIT 1), 0
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Никита Барков' AND job = 'редактор' ORDER BY id LIMIT 1), 1
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ася Шарамаева' AND job = 'редактор' ORDER BY id LIMIT 1), 2
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Глеб Кашеваров' AND job = 'редактор' ORDER BY id LIMIT 1), 3
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ирина Курако' AND job = 'редактор' ORDER BY id LIMIT 1), 4
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Софья Попова' AND job = 'редактор' ORDER BY id LIMIT 1), 5
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Вера Вересиянова' AND job = 'корректор' ORDER BY id LIMIT 1), 6
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Нелли Реук' AND job = 'корректор' ORDER BY id LIMIT 1), 7
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анастасия Давыдова' AND job = 'корректор' ORDER BY id LIMIT 1), 8
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Татьяна Максимова' AND job = 'корректор' ORDER BY id LIMIT 1), 9
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Катерина Гребенщикова' AND job = 'корректор' ORDER BY id LIMIT 1), 10
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анастасия Автухова' AND job = 'корректор' ORDER BY id LIMIT 1), 11
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Александра Крученкова' AND job = 'корректор' ORDER BY id LIMIT 1), 12
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ксения Шунькина' AND job = 'корректор' ORDER BY id LIMIT 1), 13
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Лена Солнцева' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 14
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Екатерина Ковалевская' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 15
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Кладбище Джо' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 16
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Екатерина Апенько' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 17
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анастасия Болбат' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 18
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ольга Осипова' AND job = 'дизайнер' ORDER BY id LIMIT 1), 19
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Артём Артамонов' AND job = 'дизайнер' ORDER BY id LIMIT 1), 20
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Виктория Юшина' AND job = 'верстальщик' ORDER BY id LIMIT 1), 21
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Диана Гильманова' AND job = 'верстальщик' ORDER BY id LIMIT 1), 22
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Илья Черкасов' AND job = 'веб-мастер' ORDER BY id LIMIT 1), 23
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "PrintedBookWorkers" (printed_book_id, worker_id, sort_order)
SELECT (SELECT id FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Александра Вакулинская' AND job = 'продюсер' ORDER BY id LIMIT 1), 24
WHERE EXISTS (SELECT 1 FROM "PrintedBooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-5'))
ON CONFLICT (printed_book_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;

DELETE FROM "EbookWorkers" WHERE ebook_id IN (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'));
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ирина Курако' AND job = 'редактор' ORDER BY id LIMIT 1), 0
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Ася Шарамаева' AND job = 'редактор' ORDER BY id LIMIT 1), 1
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Глеб Кашеваров' AND job = 'редактор' ORDER BY id LIMIT 1), 2
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Александра Яковлева' AND job = 'редактор' ORDER BY id LIMIT 1), 3
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Наталья Атряхайлова' AND job = 'редактор' ORDER BY id LIMIT 1), 4
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Вера Вересиянова' AND job = 'корректор' ORDER BY id LIMIT 1), 5
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Александра Каменёк' AND job = 'корректор' ORDER BY id LIMIT 1), 6
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Катерина Гребенщикова' AND job = 'корректор' ORDER BY id LIMIT 1), 7
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Софья Попова' AND job = 'корректор' ORDER BY id LIMIT 1), 8
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Полина Смолякова' AND job = 'корректор' ORDER BY id LIMIT 1), 9
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Лена Солнцева' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 10
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Маргарита Царева' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 11
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Екатерина Ковалевская' AND job = 'иллюстратор' ORDER BY id LIMIT 1), 12
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Екатерина Кравченко' AND job = 'дизайнер' ORDER BY id LIMIT 1), 13
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Диана Гильманова' AND job = 'верстальщик' ORDER BY id LIMIT 1), 14
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Анастасия Лукьянова' AND job = 'веб-мастер' ORDER BY id LIMIT 1), 15
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO "EbookWorkers" (ebook_id, worker_id, sort_order)
SELECT (SELECT id FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6') ORDER BY id LIMIT 1),
       (SELECT id FROM "Workers" WHERE name = 'Дарья Драхлер' AND job = 'продюсер' ORDER BY id LIMIT 1), 16
WHERE EXISTS (SELECT 1 FROM "Ebooks" WHERE title_id = (SELECT id FROM "Titles" WHERE slug = 'mrd-6'))
ON CONFLICT (ebook_id, worker_id) DO UPDATE SET sort_order = EXCLUDED.sort_order;

COMMIT;
