-- Periodicals — a series (e.g. «Могучий Русский Динозавр») whose issues are each
-- a Title with its own cover, editions, authors and stories, shown together on a
-- single periodical page with one section per issue.
--
-- Applied on top of the consolidated baseline (20260101000000). Idempotent so it
-- is safe to re-run; data retrofit lives in supabase/seed-periodicals.sql.

CREATE TABLE IF NOT EXISTS public."Periodicals" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    slug text,
    description text,
    sort_order integer NOT NULL DEFAULT 0,
    CONSTRAINT "Periodicals_pkey" PRIMARY KEY (id),
    CONSTRAINT "Periodicals_slug_key" UNIQUE (slug)
);

ALTER TABLE public."Periodicals" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read periodicals" ON public."Periodicals";
CREATE POLICY "Public read periodicals" ON public."Periodicals" FOR SELECT USING (true);

-- Each issue is a Title that belongs to a periodical, with a volume number + year.
ALTER TABLE public."Titles" ADD COLUMN IF NOT EXISTS periodical_id integer
    REFERENCES public."Periodicals"(id) ON DELETE SET NULL;
ALTER TABLE public."Titles" ADD COLUMN IF NOT EXISTS volume_number integer;
ALTER TABLE public."Titles" ADD COLUMN IF NOT EXISTS volume_year text;
CREATE INDEX IF NOT EXISTS titles_periodical_id_idx ON public."Titles"(periodical_id);

-- Stories belong to an issue (its Title). The issue's author list derives from
-- the distinct authors of its stories.
ALTER TABLE public."Articles" ADD COLUMN IF NOT EXISTS title_id integer
    REFERENCES public."Titles"(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS articles_title_id_idx ON public."Articles"(title_id);
