-- Align title cover filenames with objects currently stored in the public
-- Supabase Storage `covers` bucket. `Titles.cover` stores bare filenames only.

UPDATE public."Titles" AS title
SET cover = cover_map.cover
FROM (
  VALUES
    ('igra-v-mayaki', 'segamegadrive.png'),
    ('baron', 'baron.jpg'),
    ('na-zemle-zaratushtry', 'na-zemle-zaratushtry.jpg'),
    ('troe-v-lodke-ne-schitaya-harona', 'troe-v-lodke-ne-schitaya-harona.png'),
    ('serebro', 'serebro.png'),
    ('povelitel-bloh', 'povelitel-bloh.png'),
    ('doch-greha', 'doch-greha.png'),
    ('sverhderzhava', 'sverhderzhava.jpg'),
    ('gomoza', 'gomoza.jpg'),
    ('moguchij-russkij-dinozavr', 'moguchij-russkij-dinozavr.png'),
    ('segamegadrive', 'segamegadrive.png'),
    ('peterburgskie-povesty', 'peterburgskie-povesty.png'),
    ('murlo', 'murlo.jpg'),
    ('sin-greha', 'sin-greha.jpg'),
    ('kubok-voiny-i-tanca', 'kubok-voiny-i-tanca.png'),
    ('whiskey-sour', 'whiskey-sour.png'),
    ('kokora', 'kokora.jpg'),
    ('makintosh-dlya-bliznecov', 'makintosh-dlya-bliznecov.jpg'),
    ('snovidyashiy-i-snotvorishiy', 'snovidyashiy-i-snotvorishiy.png'),
    ('ob-pol', 'ob-pol.jpg'),
    ('poseiden', 'poseiden.jpg'),
    ('unhappened', 'unhappened.jpg'),
    ('vremyapadenie', 'vremyapadenie.jpg'),
    ('hudshee', 'hudshee.jpg'),
    ('gorod-sluchajnostej', 'gorod-sluchajnostej.jpg'),
    ('vihr-zhizni', 'vihr-zhizni.jpg'),
    ('prizrachnye-istorii', 'prizrachnye-istorii.jpg'),
    ('hudshee-2', 'hudshee-2.jpg'),
    ('amystis', 'amystis.jpg'),
    ('pupsiki', 'pupsiki.jpg'),
    ('rossijskoe-vremja', 'rossijskoe-vremja.jpg'),
    ('leshu-neubitiy-zhivoy', 'leshu-neubitiy-zhivoy.png'),
    ('advent-calendar', 'advent-calendar.png'),
    ('i-est-rossia', 'i-est-rossia.png'),
    ('abzac-workshop', 'abzac-workshop.png'),
    ('v-yarosti-i-pod-solyu', 'v-yarosti-i-pod-solyu.jpg'),
    ('predsetatel-tomskiy', 'predsetatel-tomskiy.jpg'),
    ('local_press', 'local_press.jpg'),
    ('olesya', 'olesya.png'),
    ('nevidimyi-drug', 'nevidimyi-drug.jpg'),
    ('glas-zemli', 'glas-zemli.png'),
    ('doctor-sax', 'doctor-sax.png'),
    ('bog-ego-imya', 'bog-ego-imya.jpg'),
    ('rossia', 'rossia.png'),
    ('overdrive', 'overdrive.jpg'),
    ('kolmi-press', 'kolmi-press.jpg'),
    ('kotlovan', 'kotlovan.jpg'),
    ('slava', 'slava.png'),
    ('dostoevski-dvoinik', 'dostoevski-dvoinik.png'),
    ('pozhninoch', 'pozhninoch.png'),
    ('dostoevskie_dni', 'dostoevskie_dni.jpg'),
    ('prostitutes', 'prostitutes.jpg'),
    ('sepiya', 'sepiya.jpg'),
    ('prizraki', 'prizraki.jpg'),
    ('irokez', 'irokez.jpg'),
    ('craft', 'craft.jpg'),
    ('podzemnie', 'podzemnie.jpg'),
    ('white-flower', 'white-flower.jpg'),
    ('smerti-net', 'smerti-net.jpg'),
    ('frieda-and-gitta', 'frieda-and-gitta.jpg'),
    ('lucifer', 'lucifer.jpg'),
    ('v-doroge', 'v-doroge.jpg'),
    ('prepodrobniy', 'prepodrobniy.jpg'),
    ('my-komu-to-nujni', 'my-komu-to-nujni.jpg')
) AS cover_map(slug, cover)
WHERE title.slug = cover_map.slug;
