name: publish

on:
  push:
    branches: [ "feature/deploy" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.actor }}/<image-name>:latest
  IMAGE_NAME: ${{ github.actor }}/chtivonext:latest
  # NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
  # NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
  # NEXT_PUBLIC_SERVICE_ROLE_KEY: ${{secrets.NEXT_PUBLIC_SERVICE_ROLE_KEY}}
  # NEXT_PUBLIC_SHOP_ID: ${{secrets.NEXT_PUBLIC_SHOP_ID}}
  # NEXT_PUBLIC_ROBOPASS_ONE: ${{secrets.NEXT_PUBLIC_ROBOPASS_ONE}}
  # NEXT_PUBLIC_ROBOPASS_TWO: ${{secrets.NEXT_PUBLIC_ROBOPASS_TWO}}
  


jobs:
    # publish:
    #     name: publish image
    #     runs-on: ubuntu-latest

    #     steps:
    #     - uses: actions/checkout@v3
    #     - name: Login
    #       run: |
    #         echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    #     - name: Build and Publish
    #       env:
    #         NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
    #         NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
    #         NEXT_PUBLIC_SERVICE_ROLE_KEY: ${{secrets.NEXT_PUBLIC_SERVICE_ROLE_KEY}}
    #         NEXT_PUBLIC_SHOP_ID: ${{secrets.NEXT_PUBLIC_SHOP_ID}}
    #         NEXT_PUBLIC_ROBOPASS_ONE: ${{secrets.NEXT_PUBLIC_ROBOPASS_ONE}}
    #         NEXT_PUBLIC_ROBOPASS_TWO: ${{secrets.NEXT_PUBLIC_ROBOPASS_TWO}}
    #       run: |
    #         docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    #         docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
           


    deploy:
        # needs: publish
        name: deploy from repo
        runs-on: ubuntu-latest

        steps:
        - name: install ssh keys
          # check this thread to understand why its needed:
          # < https://stackoverflow.com/a/70447517 >
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: connect and pull repo
          # run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker compose pull && docker compose up -d && exit"
          # run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && eval '$(ssh-agent -s)' && ssh-add ${{ secrets.SSH_PRIVATE_KEY }} && ssh -T -p 443 git@ssh.github.com && git clone git@github.com:russiandino/chtivo-next.git && exit"
          # run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && eval '$(ssh-agent -s)' && echo '$(pwd)' && ssh -T -p 443 git@ssh.github.com && git clone git@github.com:russiandino/chtivo-next.git && exit"
          # run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git clone https://${{ secrets.PAT }}@github.com/russiandino/chtivo-next.git && exit"
                                                                                                          # https://<pat>@github.com/<your account or organization>/<repo>.git
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ${{ secrets.WORK_DIR }} &&
            git clone https://${{ secrets.PAT }}@github.com/russiandino/chtivo-next.git &&
            exit"


        - name: cleanup
          run: rm -rf ~/.ssh