name: publish
run-name: ${{ github.actor }} - publish - pull - deploy frvrlop

on:
  push:
    branches: ['develop']

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.actor }}/<image-name>:latest
  # IMAGE_NAME: ${{ github.actor }}/chtivo-next
  IMAGE_NAME: ${{ github.repository }}
  NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
  SERVICE_ROLE_KEY: ${{secrets.SERVICE_ROLE_KEY}}

  NEXT_PUBLIC_SHOP_ID: ${{secrets.NEXT_PUBLIC_SHOP_ID}}
  NEXT_PUBLIC_ROBOPASS_ONE: ${{secrets.NEXT_PUBLIC_ROBOPASS_ONE}}
  NEXT_PUBLIC_ROBOPASS_TWO: ${{secrets.NEXT_PUBLIC_ROBOPASS_TWO}}
  BREVO_APIKEY: ${{secrets.BREVO_APIKEY}}

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # port: ${{ secrets.PORT }}
          port: 22
          script: |
            cd ${{ secrets.WORK_DIR }}
            cd chtivo-next
            echo "${{ env.IMAGE_NAME }}"
            echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
            echo "tags ${{ steps.meta.outputs.tags }}"
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker stop chtivo-next
            docker rm chtivo-next
            docker rmi ${{ steps.meta.outputs.tags }}
            docker pull ${{ steps.meta.outputs.tags }}
            docker run --rm -d --name chtivo-next -p 3000:3000 --network supabase_default ${{ steps.meta.outputs.tags }}
